package core

const (
	EXIT_OK = iota
	EXIT_NEED_SUDO
	EXIT_INVALID_ARGS
	EXIT_MISSING_ARGS
	EXIT_TOO_MANY_ARGS
	EXIT_FILE_NOT_FOUND
	EXIT_DEVBOX_NOT_FOUND
	EXIT_REPO_CONNECTION_FAILED
	EXIT_REPO_DOWNLOAD_FAILED
	EXIT_REPO_UPLOAD_FAILED
	EXIT_REPO_CHECK_FAILED
	EXIT_WORKSPACE_PUSH_FAILED
	EXIT_WORKSPACE_PULL_FAILED
	EXIT_WORKSPACE_STORE_FAILED
	EXIT_WORKSPACE_RESTORE_FAILED
	EXIT_UNKNOWN_ERROR
	EXIT_UNKNOWN_FATAL
)

const (
	ERR_INVALID_ARGS     = "invalid args"
	ERR_MISSING_ARGS     = "missing required argument"
	ERR_TOO_MANY_ARGS    = "too many arguments"
	ERR_FILE_NOT_FOUND   = "no such file or directory"
	ERR_DEVBOX_NOT_FOUND = "devbox not found"
	ERR_FATAL            = "fatal error"
	CONFIG_FILE          = "config.yaml"
	START_SCRIPT_FILE    = "usr/local/bin/start"
	STOP_SCRIPT_FILE     = "usr/local/bin/stop"
	APP_NAME             = "devbox"
)

const (
	ARG_TYPE_DIR = iota
	ARG_TYPE_BOOL
	ARG_TYPE_FILE
	ARG_TYPE_TARBALL
	ARG_TYPE_IP
	ARG_TYPE_COMMAND
	ARG_TYPE_DEVBOX_LIST
	ARG_TYPE_WORKSPACE_LIST
	ARG_TYPE_SESSION_LIST
)
